export enum EventType {
  PRODUCTION_STARTED = 'PRODUCTION_STARTED',
  MATERIAL_ISSUED = 'MATERIAL_ISSUED',
  PRODUCTION_COMPLETED = 'PRODUCTION_COMPLETED',
  QC_INSPECTED = 'QC_INSPECTED',
  BATCH_APPROVED = 'BATCH_APPROVED',
  BATCH_REJECTED = 'BATCH_REJECTED',
  BATCH_REWORK = 'BATCH_REWORK',
  PRODUCED_QUANTITY_AMENDED = 'PRODUCED_QUANTITY_AMENDED',
  IDENTITY_GENERATED = 'IDENTITY_GENERATED',
  IDENTITY_ASSIGNED = 'IDENTITY_ASSIGNED',
  IDENTITY_CANCELLED = 'IDENTITY_CANCELLED',
  MANUFACTURED = 'MANUFACTURED',
  PACKAGE_CREATED = 'PACKAGE_CREATED',
  PACKAGED = 'PACKAGED',
  PACKAGE_OPENED = 'PACKAGE_OPENED',
  UNIT_REMOVED = 'UNIT_REMOVED',
  DISPATCHED = 'DISPATCHED',
  RECEIVED = 'RECEIVED',
  RELOCATED = 'RELOCATED',
  RESERVED = 'RESERVED',
  SOLD = 'SOLD',
  DELIVERED = 'DELIVERED',
  RETURNED = 'RETURNED',
  RECALLED = 'RECALLED',
  QUARANTINED = 'QUARANTINED',

  RELEASED = 'RELEASED',
  EXPIRED = 'EXPIRED',
  DAMAGED = 'DAMAGED',
  DESTROYED = 'DESTROYED',
  VERIFIED = 'VERIFIED',
  CORRECTION = 'CORRECTION',
}

export const BATCH_LEVEL_EVENTS: readonly EventType[] = [
  EventType.PRODUCTION_STARTED,
  EventType.MATERIAL_ISSUED,
  EventType.PRODUCTION_COMPLETED,
  EventType.QC_INSPECTED,
  EventType.BATCH_APPROVED,
  EventType.BATCH_REJECTED,
  EventType.BATCH_REWORK,
  EventType.PRODUCED_QUANTITY_AMENDED,
];

export function isBatchLevel(type: EventType): boolean {
  return BATCH_LEVEL_EVENTS.includes(type);
}
export const RELEASE_EVENTS: readonly EventType[] = [
  EventType.DISPATCHED,
  EventType.SOLD,
];
